from .backend import FortranBackend
class SolverFacade:
    def __init__(self,library_path=None): self.backend=FortranBackend(library_path)
    def modal(self,model,speed_rad_s): return self.backend.modal_eigenvalues(model,speed_rad_s)
    def modal_eigensystem(self,model,speed_rad_s): return self.backend.modal_eigensystem(model,speed_rad_s)
    def assemble(self,model,speed_rad_s=0.0): return self.backend.assemble_matrices(model,speed_rad_s)
    def bearings(self,model,speed_rad_s): return self.backend.bearings_matrices(model,speed_rad_s)
    def frequency_response(self,model,speeds_rad_s): return self.backend.frequency_response(model,speeds_rad_s)
    def auxiliary_frequency_response(self,model,rotor_speed_rad_s,omega_rad_s,direction=1.0): return self.backend.auxiliary_frequency_response(model,rotor_speed_rad_s,omega_rad_s,direction)
    def foundation_frequency_response(self,model,rotor_speed_rad_s,omega_rad_s): return self.backend.foundation_frequency_response(model,rotor_speed_rad_s,omega_rad_s)
    def critical_speeds(self,model,**kwargs): return self.backend.critical_speeds(model,**kwargs)
    def coaxial_modal(self,model,speed_rad_s): return self.backend.coaxial_modal(model,speed_rad_s)
    def coaxial_frequency_response(self,model,speeds_rad_s): return self.backend.coaxial_frequency_response(model,speeds_rad_s)
    def asymmetric_assemble(self,model): return self.backend.asymmetric_assemble(model)
    def asymmetric_bearings(self,model): return self.backend.asymmetric_bearings(model)
    def asymmetric_modal(self,model,speed_rad_s,want_vectors=False): return self.backend.asymmetric_modal(model,speed_rad_s,want_vectors)
    def asymmetric_frequency_response(self,model,speeds_rad_s): return self.backend.asymmetric_frequency_response(model,speeds_rad_s)
